config/routes.rb
CourseProject::Application.routes.draw do
  root to: "posts#index"
  resources :posts, only: [:show, :new, :create] do
  	resources :comments, only: [:create]
  	resources :votes, only: [:create]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessible :post_id, :content
end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :url, :title

	has_many :comments
	has_many :votes

	before_create :generate_slug

	def vote_number
		votes.where(direction: "up").count - votes.where(direction: "down").count
	end

	def to_param
		slug
	end

	def generate_slug
		self.slug = title.split(' ').join('_')
	end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	attr_accessible :direction
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		post = Post.find_by_slug(params[:post_id])
		post.comments.create(params[:comment])
		redirect_to post_path(post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def show
		@post = Post.where(slug: params[:id]).first
		@comment = Comment.new
	end

	def new
		@post = Post.new
	end

	def create
		Post.create(params[:post])
		redirect_to root_path
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def create
		post = Post.find_by_slug(params[:post_id])
		post.votes.create(direction: params[:direction])
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
Navigation

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/index.html.erb
<p>
	<%= link_to "Submit a Link", new_post_path %>
</p>

<ul>
		<% @posts.each do |post| %>
			<li>
				<%= link_to post_votes_path(post, direction: "up"), :method => :post do %>
						<i class="icon-arrow-up"></i>
				<% end %>

				<span> <%= post.vote_number %> </span>

				<%= link_to post_votes_path(post, direction: 'down'), :method => :post do %>
						<i class="icon-arrow-down"></i>
				<% end %>

				<%= link_to post.title, post.url %> 
				(<%= link_to pluralize(post.comments.count, "comment"), post_path(post) %> )
			</li>
		<% end %>
</ul>

app/views/posts/new.html.erb
<h2> Submit a link here: </h2>

<%= form_tag posts_path do %>
	<%= label_tag :title, "Title" %>
	<%= text_field_tag "post[title]" %>
	<%= label_tag :url, "URL" %>
	<%= text_field_tag "post[url]" %>
	<br/>
	<%= submit_tag "Submit a Link" %>
<% end %>

app/views/posts/show.html.erb
<h2> Show a post </h2>

<p>
	<%= link_to @post.title, @post.url %>
</p>

<p> <%= pluralize(@post.comments.count, "comment") %></p>

<ul>
	<% @post.comments.each do |comment| %>
		<li>
			<%= comment.content %>
		</li>
	<% end %>
</ul>

<p>
	<h4> Create a New Comment: </h4>
	<%= form_for [@post, @comment] do |f| %>
		<%= f.label :content %>
		<%= f.text_area :content, rows: 5%>
		<br/>
		<%= f.submit "Submit This Comment" %>
	<% end %>
</p>